server:
  port: 8088
  tomcat:
    max-http-form-post-size: 40MB
    max-swallow-size: 40MB
  servlet:
    context_parameters:
      javax:
        faces:
          DATETIMECONVERTER_DEFAULT_TIMEZONE_IS_SYSTEM_TIMEZONE: true
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
    session:
      timeout: 8h
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: SpringBootLab
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
  datasource:
    #url: jdbc:mysql://localhost:3306/springboot-lab
    url: jdbc:mysql://localhost:3306/springlab
    username: springlab
    password: springlab
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  session:
    jdbc:
      initialize-schema: always
